# This file defines constraints on the direct dependencies of the Go code.
# Additionally, [[override]] blocks can define versions of transitive
# dependencies.
#
# Run `./dep.sh ensure` to generate WORKSPACE dependencies with the dep tool.

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.24.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/h2non/gock"
  version = "1.0.9"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.13.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

# This is required to ensure the CaseSensitive config is present.
# TODO(rodrigoq): find out why `dep` doesn't handle this on its own.
[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.2"

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.13.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.1.10"
